#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/capstone
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

spring:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      data-locations: classpath:/data.sql
      mode: always

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE