#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/capstone
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

spring:
  datasource:
    url: jdbc:h2:mem:testdb


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug # logger 로 출력(권장)
#  org.hibernate.type: trace