spring:
  h2:
    console:
      enabled: true #false 해야함
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#  datasource:
#    url: jdbc:mysql://basic-capstone-socialchild.c7sqiiwaofcr.eu-north-1.rds.amazonaws.com:3306/socialchilddb
#    username: root
#    password: Sbtmxkxmzpdlwldb!04250217!!
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test2
    username: sa
    password: sa


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
