#spring:
#  datasource:
#    url: jdbc:mysql://172.210.80.67:3306/CapstoneDB?characterEncoding=UTF-8&serverTimezone=UTC
#    username: CapstoneDB
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#테스트는 h2로 할예정
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/capstone
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug # logger 로 출력(권장)
#  org.hibernate.type: trace